---
substitutions:
  name: "balboa-htcs"
  friendly_name: "Hot Tub Control System"
  device_description: "Balboa Hot Tub Control System"

packages:
  balboa: !include balboa_base.yaml

climate:
  - platform: balboa
    id: balboa_climate
    name: None
