---
substitutions:
  name: "balboa"
  friendly_name: "Balboa Device"
  device_description: "Balboa Device"
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev
  github_ref: main
  # external_components_source: github://mstaiger/esphome-balboa@${github_ref}
  logger_level: WARN
  balboa_update_interval: 30s
  balboa_alarm_update_interval: 30s
  balboa_alarm_history_update_interval: 60s
  wifi_module_address: "0x340"
  external_components_source: components
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: "2024.6.0"
  platform: $platform
  board: $board
  project:
    name: "mstaiger.esphome-balboa"
    version: v2.2.0
preferences:
  flash_write_interval: "24h"
wifi:
  ap:
captive_portal:
api:
  services:
    - service: read
      variables:
        datapoint_id: string
      then:
        - lambda: id(balboa_id).homeassistant_read(datapoint_id);
    - service: read_from_address
      variables:
        datapoint_id: string
        address: int
      then:
        - lambda: id(balboa_id).homeassistant_read(datapoint_id, address);
    - service: write_enum
      variables:
        datapoint_id: string
        value: int
      then:
        - lambda: id(balboa_id).homeassistant_write(datapoint_id, (uint8_t) value);
    - service: write_enum_from_address
      variables:
        datapoint_id: string
        value: int
        address: int
      then:
        - lambda: id(balboa_id).homeassistant_write(datapoint_id, (uint8_t) value, address);
    - service: write_float
      variables:
        datapoint_id: string
        value: float
      then:
        - lambda: id(balboa_id).homeassistant_write(datapoint_id, value);
    - service: write_float_from_address
      variables:
        datapoint_id: string
        value: float
        address: int
      then:
        - lambda: id(balboa_id).homeassistant_write(datapoint_id, value, address);
ota:
  platform: esphome
logger:
  level: ${logger_level}
  tx_buffer_size: 1024
external_components:
  - source: ${external_components_source}
uart:
  id: balboa_uart
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
balboa:
  id: balboa_id
  uart_id: balboa_uart
  update_interval: ${balboa_update_interval}
  request_mod_update_intervals:
    1: ${balboa_alarm_update_interval}
    2: ${balboa_alarm_history_update_interval}
    3: ${balboa_alarm_history_update_interval}
  src_address: ${wifi_module_address}
sensor:
  - platform: balboa
    name: "Active Alerts"
    id: alarm_count
    sensor_datapoint: ALRMALRT
    request_mod: 1
    accuracy_decimals: 0
    icon: "mdi:alert"
    state_class: "measurement"
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: wifi_signal_sensor
    entity_category: "diagnostic"
