---
substitutions:
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev

# packages:
#   balboa:
#     url: https://github.com/mstaiger/esphome-balboa
#     ref: main
#     file: balboa_hot_tub_control_system.yaml
